### ISSUE TITLE
和植物魔法在服务器上同时安装的时候报错？ Work wrong with Botania in DEDICATED_SERVER?

### ISSUE THREAD

**Issue by ChensingML** [KELETU66666/ReForbiddenMagic#6]
你好，我在Forge服务器上安装mod时出现了以下报错  
Hello, I encountered a problem when I install the mod on a Forge server.  

```
[11:18:27] [Server thread/ERROR] [Lost Magic]: Schools of Magic decayed like a Daybloom.
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at keletu.forbiddenmagicre.compat.botania.RegisterHandlerBota.lexify(RegisterHandlerBota.java:77)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at keletu.forbiddenmagicre.forbiddenmagicre.init(forbiddenmagicre.java:63)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at java.lang.reflect.Method.invoke(Method.java:498)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at java.lang.reflect.Method.invoke(Method.java:498)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at java.lang.reflect.Method.invoke(Method.java:498)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[11:18:27] [Server thread/INFO] [STDERR]: [fox.spiteful.lostmagic.Lumberjack:log:12]:   at java.lang.Thread.run(Thread.java:748)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    ... 37 more
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@c8b96ec from coremod FMLCorePlugin
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:    ... 39 more
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[11:18:27] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:    ... 41 more
```

这些是我安装的所有模组：  
And here are mod I installed:  
![image](https://github.com/user-attachments/assets/fcce194f-e1f8-41ec-85dc-54be9016c840)

**Comment by KELETU66666** [comment]
OK，一会就修，谢谢反馈

**Comment by KELETU66666** [comment]
修了
